more update baxter config/launch files to run on kinetic
ros-planning/moveit_robots pull request #64
Opened 2017-10-10 09:13 UTC by k-okada

- fix to use python code in warehouse_ros_mongo and use warehouse_ros_mongo::MongoDatabaseConnection as plugin: https://github.com/ros-planning/moveit/pull/81
- add more disable_collisions
- use fixed for /world virtual_joint, so interactive marker publishes with frame_id /base
- use fake_execution of move_groups instaed of dummy_joint_trajectory_controller
- update moveit.rviz

2017-10-10 09:24 UTC, v4hn commented on baxter/baxter_moveit_config/launch/demo_dummy.launch
> -  <node name="dummy_joint_trajectory_controller" pkg="baxter_moveit_config" type="dummy_joint_trajectory_controller">
Is the `dummy_joint_trajectory_controller` still required somewhere or can we get rid of it altogether?
The interpolating demo-mode was supposed to replace these scripts wherever possible.

2017-10-10 09:24 UTC, v4hn commented on baxter/baxter_moveit_config/launch/demo_dummy.launch
> +  This corresponds to moving around the real robot without theuse of MoveIt.
typo "theuse"

2017-10-10 11:30 UTC, k-okada commented on baxter/baxter_moveit_config/launch/demo_dummy.launch
> -  <node name="dummy_joint_trajectory_controller" pkg="baxter_moveit_config" type="dummy_joint_trajectory_controller">
We do not need the script any more, so we can remove this scripts.

2017-10-10 11:31 UTC, k-okada commented on baxter/baxter_moveit_config/launch/demo_dummy.launch
> +  This corresponds to moving around the real robot without theuse of MoveIt.
fixed

2017-10-10 13:29 UTC, IanTheEngineer requested changes
Looks good overall. Thanks for your improvements, @k-okada . I'm not able to launch the `demo_dummy.launch` currently, but with that fixed, this should be good to go.

2017-10-10 13:29 UTC, IanTheEngineer commented on baxter/baxter_moveit_config/launch/move_group.launch
> +    <arg name="moveit_controller_manager" value="fake"       if="$(arg fake_execution)"/>
I'm not seeing a new `fake__moveit_controller_manager.launch` file to correspond with this new parameter value. This will cause launching `demo_dummy.launch` to fail inside of `trajectory_execution.launch`

2017-10-10 15:41 UTC, k-okada commented on baxter/baxter_moveit_config/launch/move_group.launch
> +    <arg name="moveit_controller_manager" value="fake"       if="$(arg fake_execution)"/>
@IanTheEngineer , you're right. Added missing files

2017-10-18 06:20 UTC, davetcoleman commented on baxter/baxter_moveit_config/config/baxter_base.srdf.xacro
> +    <virtual_joint name="world_joint" type="fixed" parent_frame="world" child_link="base" />
is this necessary? it makes it hard to "hide" the robot as I do in moveit_visual_tools and it requires you to use /tf to move the robots in other locations in the world

2017-10-18 09:50 UTC, k-okada commented on baxter/baxter_moveit_config/config/baxter_base.srdf.xacro
> +    <virtual_joint name="world_joint" type="fixed" parent_frame="world" child_link="base" />
I could not display interactive marker to control end defectors without this change, because of  missing 'world' frame in `tf`. Should we use '/base` as the fixed frame at https://github.com/ros-planning/moveit_robots/blob/kinetic-devel/baxter/baxter_moveit_config/launch/moveit.rviz#L685, or is there some bugs on interactive marker section.?

2017-10-18 17:47 UTC, davetcoleman commented on baxter/baxter_moveit_config/config/baxter_base.srdf.xacro
> +    <virtual_joint name="world_joint" type="fixed" parent_frame="world" child_link="base" />
i believe you would need to add a [static_transform_publisher](http://wiki.ros.org/static_transform_publisher) to fix the missing world frame

2017-10-20 09:12 UTC, k-okada commented on baxter/baxter_moveit_config/config/baxter_base.srdf.xacro
> +    <virtual_joint name="world_joint" type="fixed" parent_frame="world" child_link="base" />
@davetcoleman ok I have updated the code, btw On Baxter robot, `getRobotState()->getModelFrame()` returns `world` and `getRootLink() returns `base`. It is expected behavior? If we use 'getRootLink()` in [robot_interaction.cpp](https://github.com/ros-planning/moveit/blob/kinetic-devel/moveit_ros/robot_interaction/src/robot_interaction.cpp#L483), or [skip 'floating' joint](https://github.com/ros-planning/moveit/blob/kinetic-devel/moveit_core/robot_model/src/robot_model.cpp#L921), may be we do not need to add static_transform_publisher

2017-10-24 19:08 UTC, IanTheEngineer requested changes
I took a second pass at testing this, and found duplicate collision disables. Once they are removed, this can be merged. Thanks again for your PR!

2017-10-24 19:08 UTC, IanTheEngineer commented on baxter/baxter_moveit_config/config/baxter_base.srdf.xacro
> +    <disable_collisions link1="r_gripper_r_finger" link2="r_gripper_r_finger_tip" reason="Adjacent" />
All of the collisions from here down are already added in `rethink_electric_gripper.srdf.xacro` which is invoked by `baxter.srdf.xacro` if `right_electric_gripper` or `left_electric_gripper` args are set to `true`. These duplicate lines should be removed, but the `sonar_ring <--> torso` disable can be kept if you like.

2017-10-24 20:35 UTC, IanTheEngineer commented
I think https://github.com/RethinkRobotics/baxter_common/pull/90 will help out in testing this PR: it makes the electric_grippers optional.

2017-10-26 10:46 UTC, k-okada commented
ok, change 'demo_dummy.launch` set  electric gripper true by default. Should we change `demo_baxter.launch` too ? otherwise , moveit will not work just start 'demo_baster.launch` and that will confuse a  lot of people.

2017-10-26 16:09 UTC, IanTheEngineer commented
> ok, change 'demo_dummy.launchset electric gripper true by default. Should we changedemo_baxter.launchtoo ? otherwise , moveit will not work just start 'demo_baster.launch and that will confuse a lot of people.

The [`baxter_grippers.launch`](https://github.com/ros-planning/moveit_robots/blob/kinetic-devel/baxter/baxter_moveit_config/launch/baxter_grippers.launch) launch file serves the purpose of "grippers on by default" for the SRDF with the real robot. Hopefully the [Baxter MoveIt tutorial](http://sdk.rethinkrobotics.com/wiki/MoveIt_Tutorial#Tutorial) makes that clear. On the real robot, we don't want to construct the URDF, as we should be relying on Baxter's own parameter server to supply the `robot_description` param. Baxter will correctly update it's URDF (but not SRDF) if a gripper is plugged or unplugged from the robot.

I don't think you need to change the gripper defaults for `demo_dummy.launch`. Without a real Baxter robot, the https://github.com/RethinkRobotics/baxter_common/pull/90 pull request that I referred to will help properly construct the correct URDF to account for grippers or no grippers, at the same time the SRDF is constructed inside the `demo_dummy.launch`.

2017-10-27 01:45 UTC, k-okada commented
ok, removed the last commit @IanTheEngineer

2017-10-27 13:43 UTC, IanTheEngineer approved these changes
Looks great! Thank you for iterating on the updates @k-okada. I have one minor comment on adding back in a collision. That aside, I think this PR is fine to merge.

2017-10-27 13:43 UTC, IanTheEngineer commented on baxter/baxter_moveit_config/config/baxter_base.srdf.xacro
> -    <disable_collisions link1="sonar_ring" link2="torso" reason="Adjacent" />
@k-okada it appears that this disable was originally here and just now removed? If that's the case, we should likely leave it intact.

2017-11-02 01:56 UTC, k-okada commented on baxter/baxter_moveit_config/config/baxter_base.srdf.xacro
> -    <disable_collisions link1="sonar_ring" link2="torso" reason="Adjacent" />
@IanTheEngineer sorry for late, that was removed unintentionally, fixed in latest commit

2017-11-02 23:35 UTC, davetcoleman commented
Fix for broken build: https://github.com/ros-planning/moveit_robots/pull/66

2017-11-06 16:37 UTC, merged